---
site_name: libigl
site_url: 'https://libigl.github.io/'
repo_name: 'libigl/libigl'
repo_url: 'https://github.com/libigl/libigl'
edit_uri: '../libigl.github.io/edit/docs/docs/'
site_description: "Simple C++ geometry processing library"
# strict: true
docs_dir: 'docs'
remote_branch: 'master'
theme:
  name: material
  favicon: 'favicon.ico'
  logo: 'logo.png'
  palette:
    primary: 'light blue'
    accent: 'blue'
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/libigl'
  repo_url: 'https://github.com/libigl/libigl/tree/main'
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'css/style.css'
  - 'css/pygments.css'
markdown_extensions:
  - codehilite:
      guess_lang: false
  - footnotes
  - admonition
  - toc:
      permalink: true
  - figureAltCaption
  - markdown.extensions.smarty
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.wikilinks:
      base_url: https://github.com/libigl/libigl/tree/main
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
      user: libigl
      repo: libigl
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
  - macros:
      verbose: true
  - redirects:
      redirect_maps:
        'RELEASE_HISTORY.md': 'changelog.md'
        'LICENSE.md': 'license.md'
        'CONTRIBUTING.md': 'bug-report.md'
        'upgrade-v2-to-v3.md': 'changelog.md'
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - Python Bindings: python-bindings.md
  - Compilation:
      - Example Project: example-project.md
      - Static Library: static-library.md
      - External Dependencies: third-party.md
  - Contributing:
      - Style Guidelines: style-guidelines.md
      - Bug Report: bug-report.md
      - Creating a Pull Request: before-submitting-pull-request.md
      - Unit Tests: unit-tests.md
  - Misc:
      - Matlab-libigl Cheatsheet: matlab-to-eigen.md
      - Coding Tips: coding-guidelines.md
      - File Formats:
          - Index: file-formats/index.md
          - bf: file-formats/bf.md
          - dmat: file-formats/dmat.md
          - rbr: file-formats/rbr.md
          - tgf: file-formats/tgf.md
          - xml: file-formats/xml.md
      - Building the Website: website.md
      - Rewritten History: rewritten-history.md
  - FAQ: faq.md
  - About:
      - Changelog: changelog.md
      - License: license.md
